// config.js
const CONFIG = {
  GOOGLE_MAPS_API_KEY: "",

  // 成本控制
  MAX_RECT_AREA_KM2: 5.0,
  MAX_RESTAURANT_RESULTS: 80,
  MAX_RESTAURANT_RADIUS_M: 2500,
  MAX_ATTRACTION_RESULTS_PER_RESTAURANT: 40,
  DETAILS_CONCURRENCY: 4,

  // 路徑估算
  DEFAULT_RADIUS: 500,
  TRAVEL_SPEED_M_PER_MIN: 250,
  DINING_DURATION_MIN: 50,
  CLOSE_BUFFER_MIN: 30,

  // cost(u, v) 權重
  INF_COST: 1e9,
  RATING_WEIGHT: 12,
  TRAVEL_WEIGHT: 0.08,

  // 候選與隨機
  MAX_CANDIDATE_PER_MEAL: 20,
  TOP_RANDOM_POOL: 8,
  MAX_RANDOM_PICK_PER_SEGMENT: 3,
  MAX_MANUAL_PICK_PER_SEGMENT: 4,
  MAX_SHOW_CANDIDATES_PER_SEGMENT: 20
};
